# Generated by Django 5.1.4 on 2024-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(null=b'I01\n')),
                ('address', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(null=True)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
    ]
