# Generated by Django 5.1.4 on 2024-12-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_doctor_alter_patient_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
