# Generated by Django 5.1.4 on 2024-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='diploma_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
