# Generated by Django 5.1.4 on 2024-12-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0005_appointment_time_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
